name: Deploy to VPS

on:
  push:
    branches: [ "develop" ]

env:
  VPS_PROJECT_PATH: /home/readers-journal
  REPO_BRANCH: develop

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e  # Выход при ошибке
            
            echo "Updating repository..."
            cd $VPS_PROJECT_PATH
            git fetch
            git checkout $REPO_BRANCH
            git pull origin $REPO_BRANCH
            
            echo "Installing backend dependencies..."
            cd backend
            npm ci --production
            
            echo "Restarting PM2 process..."
            pm2 restart readers-journal-backend --update-env
            
            echo "Backend deployment completed successfully!"
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e  # Выход при ошибке
            
            echo "Updating repository..."
            cd $VPS_PROJECT_PATH
            git fetch
            git checkout $REPO_BRANCH
            git pull origin $REPO_BRANCH

            echo "Installing frontend dependencies..."
            cd frontend
            npm ci
            
            echo "Building frontend..."
            npm run build
            
            echo "Testing and restarting Nginx..."
            sudo nginx -t
            sudo systemctl restart nginx
            
            echo "Frontend deployment completed successfully!"