name: Deploy to VPS

on:
  push:
    branches: [ "develop" ]  # Триггер на пуш в develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/readers-journal/frontend
            git pull origin develop
            npm install
            npm run build
            sudo nginx -t && sudo systemctl restart nginx
