name: Deploy to VPS

on:
  push:
    branches: [ "develop" ]  # Триггер на пуш в develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Обновляем репозиторий
            cd /home/readers-journal
            git pull origin develop
            
            # Фронтенд часть
            cd frontend
            npm install
            npm run build
            
            # Бэкенд часть
            cd ../backend
            npm install
            
            # Перезапускаем PM2 процесс
            pm2 restart readers-journal-backend --update-env
            
            # Перезапускаем Nginx    
            sudo nginx -t && sudo systemctl restart nginx
